language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git zip

script:
  - cd $HOME
  - git config --global user.name "ShanuDey"
  - git config --global user.email "sd4shanudey@gmail.com"
  - git config --global color.ui false
  - mkdir kernel && cd kernel
  - wget https://raw.githubusercontent.com/X00T-Development/kernel-travis/master/build.sh
  - source build.sh
